
services:
  db:
    restart: always
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env.dev
    ports:
      - 5432
  web:
    restart: always
    build: .
    env_file:
      - .env.dev
    environment:
      - DEBUG=1
    command: python manage.py runserver 0.0.0.0:80
    volumes:
      - .:/code
    ports:
      - "80:80"

volumes:
  postgres_data:
