# Generated by Django 2.2.2 on 2019-06-29 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pageview',
            options={'ordering': ('-timestamp',)},
        ),
    ]
