# Generated by Django 2.2.2 on 2019-06-29 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0003_search'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='search',
            options={'ordering': ('-search_timestamp',), 'verbose_name_plural': 'searches'},
        ),
    ]
