# Generated by Django 2.2.2 on 2019-06-20 00:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0007_auto_20190518_0230'),
    ]

    operations = [
        migrations.CreateModel(
            name='EssentialQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Metric',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('essential_question', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='high_health.EssentialQuestion')),
                ('report', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.Report')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
    ]
