# Generated by Django 2.2.2 on 2019-06-20 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('high_health', '0002_school_schoollevel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal_type', models.CharField(choices=[('ABOVE', 'above'), ('BELOW', 'below')], max_length=5)),
                ('value', models.DecimalField(decimal_places=2, max_digits=5)),
                ('date', models.DateTimeField(auto_now=True)),
                ('metric', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='high_health.Metric')),
            ],
            options={
                'ordering': ['-date', 'school', 'metric'],
            },
        ),
        migrations.AlterModelOptions(
            name='school',
            options={'ordering': ('name',)},
        ),
        migrations.CreateModel(
            name='Measure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=2, max_digits=5)),
                ('date', models.DateTimeField(auto_now=True)),
                ('goal', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='high_health.Goal')),
                ('metric', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='high_health.Metric')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='high_health.School')),
            ],
            options={
                'ordering': ['-date', 'school', 'metric'],
            },
        ),
        migrations.AddField(
            model_name='goal',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='high_health.School'),
        ),
    ]
