# Generated by Django 2.2.2 on 2019-06-20 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('high_health', '0004_auto_20190620_1818'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='growth',
            field=models.IntegerField(default=0),
        ),
    ]
