# Generated by Django 2.2.2 on 2019-06-21 04:12

from django.db import migrations, models
import high_health.models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_auto_20190621_0255"),
        ("high_health", "0006_auto_20190620_1901"),
    ]

    operations = [
        migrations.AddField(
            model_name="metric",
            name="school_level",
            field=models.ManyToManyField(to="accounts.SchoolLevel"),
        )
    ]
