# Generated by Django 2.2.2 on 2019-06-21 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('high_health', '0007_metric_school_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='measure',
            name='is_current',
            field=models.BooleanField(default=True),
        ),
    ]
