# Generated by Django 2.2.3 on 2019-07-29 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('high_health', '0009_auto_20190729_1635'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='metric',
            name='goal_type',
        ),
        migrations.RemoveField(
            model_name='metric',
            name='growth_goal',
        ),
        migrations.RemoveField(
            model_name='metric',
            name='performance_goal',
        ),
        migrations.RemoveField(
            model_name='metric',
            name='school_level',
        ),
    ]
