# Generated by Django 2.2.3 on 2019-07-29 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('high_health', '0010_auto_20190729_1700'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='metric',
            name='goals',
        ),
    ]
