# Generated by Django 2.2.4 on 2019-09-05 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('high_health', '0011_remove_metric_goals'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goal',
            name='frequency',
        ),
        migrations.AddField(
            model_name='metric',
            name='frequency',
            field=models.CharField(choices=[('MoM', 'month over month'), ('YoY', 'year over year')], default='MoM', max_length=3),
        ),
    ]
