# Generated by Django 2.2.5 on 2019-09-19 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('high_health', '0013_auto_20190906_1349'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='previous_outcome',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=5),
        ),
    ]
