# Generated by Django 4.2.23 on 2025-08-07 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('high_health', '0014_goal_previous_outcome'),
    ]

    operations = [
        migrations.AddField(
            model_name='metric',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
