# Generated by Django 2.2.1 on 2019-05-15 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_profile_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='employee_number',
            field=models.CharField(blank=True, max_length=5),
        ),
    ]
