# Generated by Django 2.2.1 on 2019-05-18 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_auto_20190518_0230'),
        ('accounts', '0004_auto_20190515_2035'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='favorites',
            field=models.ManyToManyField(through='catalog.Favorite', to='catalog.Report'),
            preserve_default=False,
        ),
    ]
