# Generated by Django 2.2.3 on 2019-07-24 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20190621_0255'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoollevel',
            name='display_name',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
