# Generated by Django 2.2.5 on 2019-09-19 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('accounts', '0009_role_role_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='permission_group',
            field=models.ManyToManyField(to='auth.Group'),
        ),
    ]
