# Generated by Django 3.2 on 2021-04-26 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_auto_20200929_0856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='employee_number',
            field=models.CharField(max_length=5, unique=True),
        ),
    ]
