# Generated by Django 4.2.16 on 2025-04-11 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_alter_profile_first_name_alter_profile_last_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TableauPermissionsGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_id', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.AddField(
            model_name='job',
            name='tableau_permissions',
            field=models.ManyToManyField(blank=True, to='accounts.tableaupermissionsgroup'),
        ),
        migrations.AddField(
            model_name='profile',
            name='base_tableau_permissions',
            field=models.ManyToManyField(blank=True, related_name='base_permissions', to='accounts.tableaupermissionsgroup'),
        ),
        migrations.AddField(
            model_name='profile',
            name='tableau_permission_exceptions',
            field=models.ManyToManyField(blank=True, related_name='permission_exceptions', to='accounts.tableaupermissionsgroup'),
        ),
        migrations.AddField(
            model_name='site',
            name='tableau_permissions',
            field=models.ManyToManyField(blank=True, to='accounts.tableaupermissionsgroup'),
        ),
    ]
