# Generated by Django 4.2.16 on 2025-05-19 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_tableaupermissionsgroup_job_tableau_permissions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='tableau_permissions',
            field=models.ManyToManyField(blank=True, null=True, to='accounts.tableaupermissionsgroup'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='base_tableau_permissions',
            field=models.ManyToManyField(blank=True, null=True, related_name='base_permissions', to='accounts.tableaupermissionsgroup'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='tableau_permission_exceptions',
            field=models.ManyToManyField(blank=True, null=True, related_name='permission_exceptions', to='accounts.tableaupermissionsgroup'),
        ),
        migrations.AlterField(
            model_name='site',
            name='tableau_permissions',
            field=models.ManyToManyField(blank=True, null=True, to='accounts.tableaupermissionsgroup'),
        ),
    ]
