# Generated by Django 4.2.23 on 2025-08-07 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_alter_job_tableau_permissions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
