# Generated by Django 4.2.23 on 2025-08-27 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_site_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoollevel',
            name='name',
            field=models.CharField(max_length=3),
        ),
    ]
