# Generated by Django 4.2.23 on 2025-10-14 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_alter_schoollevel_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_contractor',
            field=models.BooleanField(default=False),
        ),
    ]
