# Generated by Django 4.2.23 on 2026-01-08 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_profile_is_contractor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='is_contractor',
            field=models.BooleanField(default=False, help_text='Denotes if the profile belongs to a contractor.If checked, the profile will not be deactivated by the Galaxy connector.'),
        ),
    ]
