# Generated by Django 4.2.23 on 2026-02-06 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_profile_contractor_end_date_profile_contractor_note_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='contractor_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='contractor_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='permission_exceptions_note',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='tableau_permissions',
            field=models.ManyToManyField(blank=True, to='accounts.tableaupermissionsgroup'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='base_tableau_permissions',
            field=models.ManyToManyField(blank=True, related_name='base_permissions', to='accounts.tableaupermissionsgroup'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='is_contractor',
            field=models.BooleanField(default=False, help_text='Denotes if the profile belongs to a contractor.If checked, the profile will not be deactivated by the Galaxy connector.'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='tableau_permission_exceptions',
            field=models.ManyToManyField(blank=True, related_name='permission_exceptions', to='accounts.tableaupermissionsgroup'),
        ),
        migrations.AlterField(
            model_name='site',
            name='tableau_permissions',
            field=models.ManyToManyField(blank=True, to='accounts.tableaupermissionsgroup'),
        ),
    ]
