# Generated by Django 4.2.23 on 2026-01-08 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_alter_profile_is_contractor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='tableau_permissions',
            field=models.ManyToManyField(blank=True, null=True, related_name='job_permissions', to='accounts.tableaupermissionsgroup'),
        ),
        migrations.AlterField(
            model_name='site',
            name='tableau_permissions',
            field=models.ManyToManyField(blank=True, null=True, related_name='site_permissions', to='accounts.tableaupermissionsgroup'),
        ),
    ]
