# Generated by Django 4.2.23 on 2026-02-26 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_profile_contractor_end_date_profile_contractor_note_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='tableau_permissions',
            field=models.ManyToManyField(blank=True, related_name='job_permissions', to='accounts.tableaupermissionsgroup'),
        ),
        migrations.AlterField(
            model_name='site',
            name='tableau_permissions',
            field=models.ManyToManyField(blank=True, related_name='site_permissions', to='accounts.tableaupermissionsgroup'),
        ),
    ]
