# Generated by Django 4.2.23 on 2026-02-27 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('accounts', '0024_alter_job_tableau_permissions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='galaxy_permission_groups',
            field=models.ManyToManyField(blank=True, to='auth.group'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='is_contractor',
            field=models.BooleanField(default=False, help_text='Denotes if the profile belongs to a contractor.'),
        ),
    ]
