# Generated by Django 4.2.23 on 2026-03-01 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_job_galaxy_permission_groups_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='role',
        ),
    ]
