# Generated by Django 2.2.1 on 2019-05-17 16:34

import catalog.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20190515_2035'),
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('url', models.CharField(max_length=2000)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_embedded', models.BooleanField(default=True)),
                ('category', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='catalog.Category')),
                ('roles', models.ManyToManyField(default=catalog.models.Report.roles_default, to='accounts.Role')),
                ('sites', models.ManyToManyField(default=catalog.models.Report.sites_default, to='accounts.Site')),
                ('subcategory', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='catalog.SubCategory')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
    ]
