# Generated by Django 2.2.1 on 2019-05-18 02:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_auto_20190518_0155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='catalog.Category'),
        ),
        migrations.AlterField(
            model_name='report',
            name='subcategory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='catalog.SubCategory'),
        ),
    ]
