# Generated by Django 2.2.1 on 2019-05-18 02:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_auto_20190518_0219'),
    ]

    operations = [
        migrations.AddField(
            model_name='favorite',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Profile'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='favorite',
            unique_together={('profile', 'report')},
        ),
        migrations.RemoveField(
            model_name='favorite',
            name='user',
        ),
    ]
