# Generated by Django 2.2.4 on 2019-08-09 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_auto_20190518_0230'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicStat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric', models.CharField(max_length=255)),
                ('value', models.IntegerField()),
            ],
        ),
    ]
