# Generated by Django 2.2.4 on 2019-09-04 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_auto_20190811_1215'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='is_tabbed',
            field=models.BooleanField(default=False),
        ),
    ]
