# Generated by Django 4.2.23 on 2026-02-05 02:29

import catalog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_profile_contractor_end_date_profile_contractor_note_and_more'),
        ('catalog', '0011_auto_20210804_1650'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='tableau_permissions_groups',
            field=models.ManyToManyField(default=catalog.models.Report.roles_default, to='accounts.tableaupermissionsgroup'),
        ),
    ]
