# Generated by Django 4.2.23 on 2026-01-08 17:49

import catalog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_alter_profile_is_contractor'),
        ('catalog', '0011_auto_20210804_1650'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='tableau_permissions',
            field=models.ManyToManyField(default=catalog.models.Report.tableau_permissions_default, to='accounts.tableaupermissionsgroup'),
        ),
    ]
