# Generated by Django 4.2.23 on 2026-02-27 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_alter_job_tableau_permissions_and_more'),
        ('catalog', '0012_report_tableau_permissions_groups'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='tableau_permissions_groups',
            field=models.ManyToManyField(blank=True, to='accounts.tableaupermissionsgroup'),
        ),
    ]
