# Generated by Django 4.2.23 on 2026-03-01 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0013_alter_report_tableau_permissions_groups'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='roles',
        ),
    ]
